FROM node:latest

LABEL maintainer="acs Developer"

RUN mkdir -p /acs-sms-gateway
RUN rm -r /acs-sms-gateway
RUN mkdir -p /acs-sms-gateway

WORKDIR /acs-sms-gateway
COPY node_modules /acs-sms-gateway

COPY . .

EXPOSE 5000
EXPOSE 6379