version: '3.0'

services: 

  app:
    build: 
      context: ./
    command: bash -c "npm i && node index.js"
    container_name: acs-sms-gateway
    networks:
      - sms-network
    volumes:
      - ./:/acs-sms-gateway
      - /acs-sms-gateway/node_modules
    ports:
      - "23002:23002"
    depends_on:
        - rabbitmq
    restart: always

  rabbitmq:
    container_name: acs-sms-gateway-rabbitmq
    tty: true
    image: rabbitmq:3-management
    ports: 
      - "15672:15672"
      - "15671:15671"
      - "5672:5672"
    volumes:
      - ./rabbitmq/lib:/var/lib/rabbitmq
    networks:
      - sms-network
    
networks:
  sms-network:
    driver: bridge      