version: '3.0'

volumes:
  mongodb:

services: 
  app:
    build: 
      context: ./
    command: bash -c "node index.js"
    container_name: acs-sms-gateway
    networks:
      - sms-network
    ports:
      - "23002:23002"
    depends_on:
        - mongo
    restart: always

  mongo:
    image: mongo
    container_name: acs-sms-gateway-mongo
    ports: 
      - "27017:27017"
    volumes:
      - mongodb:/data/db 
    networks:
      - sms-network
    logging:
      driver: none
    restart: always
    
networks:
  sms-network:
    driver: bridge      